<?php

declare(strict_types=1);

use Drupal\Core\Cache\RefinableCacheableDependencyInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements \hook_help().
 */
function omnipedia_menu_help($routeName, RouteMatchInterface $routeMatch) {
  return \Drupal::service('omnipedia_menu.help')->help(
    $routeName, $routeMatch
  );
}

/**
 * Implements \hook_menu_local_tasks_alter().
 */
function omnipedia_menu_menu_local_tasks_alter(
  array &$data, string $routeName,
  RefinableCacheableDependencyInterface &$cacheability
): void {
  \Drupal::service('omnipedia_menu.wiki_node_local_tasks_alter')->alter(
    $data, $routeName, $cacheability
  );
}
